export const REMOTE_SEARCH_START = "REMOTE_SEARCH_START";
export const REMOTE_SEARCH_FULFILLED = "REMOTE_SEARCH_FULFILLED";
export const CLEAR_SEARCH_RESULT = "CLEAR_SEARCH_RESULT";
export const CLEAR_SEARCH_RESULT_FULFILLED = "CLEAR_SEARCH_RESULT_FULFILLED";
export const AUTOCOMPLETE_UPDATE_START = "AUTOCOMPLETE_UPDATE_START";
export const AUTOCOMPLETE_UPDATE_FULFILLED = "AUTOCOMPLETE_UPDATE_FULFILLED";
