export const REMOTE_SEARCH_START = "REMOTE_SEARCH_START";
export const REMOTE_SEARCH_FULFILLED = "REMOTE_SEARCH_FULFILLED";
export const AUTOCOMPLETE_UPDATE_START = "AUTOCOMPLETE_UPDATE_START";
export const AUTOCOMPLETE_UPDATE_FULFILLED = "AUTOCOMPLETE_UPDATE_FULFILLED";
